SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for game_stats
-- ----------------------------
DROP TABLE IF EXISTS `game_stats`;
CREATE TABLE `game_stats` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `createDate` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `player_id` int(11) DEFAULT NULL,
  `competitive` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `time_played` float unsigned NOT NULL DEFAULT '0',
  `eliminations` mediumint(8) unsigned NOT NULL DEFAULT '0',
  `solo_kills` smallint(5) unsigned NOT NULL DEFAULT '0',
  `final_blows` mediumint(8) unsigned NOT NULL DEFAULT '0',
  `healing_done_most_in_game` smallint(5) unsigned NOT NULL DEFAULT '0',
  `medals_silver` smallint(5) unsigned NOT NULL DEFAULT '0',
  `kill_streak_best` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `defensive_assists_most_in_game` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `cards` smallint(5) unsigned NOT NULL DEFAULT '0',
  `recon_assists` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `kpd` float unsigned NOT NULL DEFAULT '0',
  `objective_kills_most_in_game` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `melee_final_blows_most_in_game` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `turrets_destroyed` smallint(5) unsigned NOT NULL DEFAULT '0',
  `teleporter_pads_destroyed_most_in_game` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `time_spent_on_fire_most_in_game` float unsigned NOT NULL DEFAULT '0',
  `medals_bronze` smallint(5) unsigned NOT NULL DEFAULT '0',
  `recon_assists_most_in_game` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `objective_time` float unsigned NOT NULL DEFAULT '0',
  `hero_damage_done` int(10) unsigned NOT NULL DEFAULT '0',
  `offensive_assists_most_in_game` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `all_damage_done_most_in_game` smallint(5) unsigned NOT NULL DEFAULT '0',
  `environmental_kills` smallint(5) unsigned NOT NULL DEFAULT '0',
  `multikills` smallint(5) unsigned NOT NULL DEFAULT '0',
  `time_spent_on_fire` float unsigned NOT NULL DEFAULT '0',
  `games_played` smallint(5) unsigned NOT NULL DEFAULT '0',
  `games_won` smallint(5) unsigned NOT NULL DEFAULT '0',
  `games_tied` smallint(5) unsigned NOT NULL DEFAULT '0',
  `games_lost` smallint(5) unsigned NOT NULL DEFAULT '0',
  `defensive_assists` mediumint(8) unsigned NOT NULL DEFAULT '0',
  `deaths` mediumint(8) unsigned NOT NULL DEFAULT '0',
  `offensive_assists` smallint(5) unsigned NOT NULL DEFAULT '0',
  `healing_done` int(10) unsigned NOT NULL DEFAULT '0',
  `eliminations_most_in_game` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `barrier_damage_done` int(10) unsigned NOT NULL DEFAULT '0',
  `objective_kills` mediumint(8) unsigned NOT NULL DEFAULT '0',
  `final_blows_most_in_game` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `medals_gold` smallint(5) unsigned NOT NULL DEFAULT '0',
  `medals` smallint(5) unsigned NOT NULL DEFAULT '0',
  `all_damage_done` int(10) unsigned NOT NULL DEFAULT '0',
  `turrets_destroyed_most_in_game` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `objective_time_most_in_game` float unsigned NOT NULL DEFAULT '0',
  `melee_final_blows` smallint(5) unsigned NOT NULL DEFAULT '0',
  `solo_kills_most_in_game` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `teleporter_pads_destroyed` smallint(5) unsigned NOT NULL DEFAULT '0',
  `environmental_kills_most_in_game` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `multikill_best` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `hero_damage_done_most_in_game` smallint(5) unsigned NOT NULL DEFAULT '0',
  `barrier_damage_done_most_in_game` smallint(5) unsigned NOT NULL DEFAULT '0',
  `damage_done` int(10) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `createDate` (`createDate`),
  KEY `competitive` (`competitive`),
  KEY `player_id, competitive, createDate` (`player_id`,`competitive`,`createDate`),
  CONSTRAINT `FK_game_stats_players` FOREIGN KEY (`player_id`) REFERENCES `players` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=63751 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for hero_general_stats
-- ----------------------------
DROP TABLE IF EXISTS `hero_general_stats`;
CREATE TABLE `hero_general_stats` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `createDate` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `player_id` int(11) NOT NULL,
  `competitive` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `hero` varchar(10) NOT NULL,
  `games_played` smallint(4) unsigned NOT NULL,
  `games_won` smallint(4) unsigned NOT NULL,
  `games_lost` smallint(4) unsigned NOT NULL,
  `games_tied` smallint(4) unsigned NOT NULL,
  `win_percentage` float unsigned NOT NULL,
  `time_played` float unsigned NOT NULL,
  `eliminations` mediumint(6) unsigned NOT NULL DEFAULT '0',
  `eliminations_most_in_life` smallint(5) unsigned NOT NULL DEFAULT '0',
  `eliminations_most_in_game` smallint(5) unsigned NOT NULL DEFAULT '0',
  `eliminations_per_life` smallint(5) unsigned NOT NULL DEFAULT '0',
  `deaths` mediumint(5) unsigned NOT NULL DEFAULT '0',
  `environmental_kills` smallint(5) unsigned NOT NULL DEFAULT '0',
  `multikills` smallint(5) unsigned NOT NULL DEFAULT '0',
  `multikill_best` smallint(5) unsigned NOT NULL DEFAULT '0',
  `objective_kills` smallint(5) unsigned NOT NULL DEFAULT '0',
  `objective_kills_most_in_game` smallint(5) unsigned NOT NULL DEFAULT '0',
  `solo_kills` smallint(5) unsigned NOT NULL DEFAULT '0',
  `solo_kills_most_in_game` smallint(5) unsigned NOT NULL DEFAULT '0',
  `kill_streak_best` smallint(5) unsigned NOT NULL DEFAULT '0',
  `final_blows` smallint(5) unsigned NOT NULL DEFAULT '0',
  `final_blows_most_in_game` smallint(5) unsigned NOT NULL DEFAULT '0',
  `critical_hits` mediumint(6) unsigned NOT NULL DEFAULT '0',
  `critical_hits_most_in_life` smallint(5) unsigned NOT NULL DEFAULT '0',
  `critical_hits_most_in_game` smallint(5) unsigned NOT NULL DEFAULT '0',
  `critical_hit_accuracy` float unsigned NOT NULL DEFAULT '0',
  `cards` smallint(5) unsigned NOT NULL DEFAULT '0',
  `medals` smallint(5) unsigned NOT NULL DEFAULT '0',
  `medals_bronze` smallint(5) unsigned NOT NULL DEFAULT '0',
  `medals_silver` smallint(5) unsigned NOT NULL DEFAULT '0',
  `medals_gold` smallint(5) unsigned NOT NULL DEFAULT '0',
  `weapon_accuracy` float unsigned NOT NULL DEFAULT '0',
  `weapon_accuracy_best_in_game` float unsigned NOT NULL DEFAULT '0',
  `all_damage_done` mediumint(12) unsigned NOT NULL DEFAULT '0',
  `all_damage_done_most_in_game` mediumint(6) unsigned NOT NULL DEFAULT '0',
  `all_damage_done_most_in_life` mediumint(6) unsigned NOT NULL DEFAULT '0',
  `hero_damage_done` mediumint(12) unsigned NOT NULL DEFAULT '0',
  `hero_damage_done_most_in_game` smallint(5) unsigned NOT NULL DEFAULT '0',
  `hero_damage_done_most_in_life` smallint(5) unsigned NOT NULL DEFAULT '0',
  `barrier_damage_done` mediumint(12) unsigned NOT NULL DEFAULT '0',
  `barrier_damage_done_most_in_game` smallint(5) unsigned NOT NULL DEFAULT '0',
  `healing_done` int(12) unsigned NOT NULL DEFAULT '0',
  `healing_done_most_in_game` smallint(5) unsigned NOT NULL DEFAULT '0',
  `objective_time` float unsigned NOT NULL DEFAULT '0',
  `objective_time_most_in_game` float unsigned NOT NULL DEFAULT '0',
  `time_spent_on_fire` float unsigned NOT NULL DEFAULT '0',
  `time_spent_on_fire_most_in_game` float unsigned NOT NULL DEFAULT '0',
  `melee_final_blows` smallint(5) unsigned NOT NULL DEFAULT '0',
  `melee_final_blows_most_in_game` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `defensive_assists` smallint(5) unsigned NOT NULL DEFAULT '0',
  `defensive_assists_most_in_game` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `offensive_assists` smallint(5) unsigned NOT NULL DEFAULT '0',
  `offensive_assists_most_in_game` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `recon_assists` smallint(5) unsigned NOT NULL DEFAULT '0',
  `recon_assists_most_in_game` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `teleporter_pads_destroyed` smallint(4) unsigned NOT NULL DEFAULT '0',
  `turrets_destroyed` smallint(5) unsigned NOT NULL DEFAULT '0',
  `quick_melee_accuracy` float unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `player_id, competitive` (`player_id`,`competitive`),
  KEY `hero` (`hero`),
  KEY `competitive` (`competitive`),
  KEY `player_id, competitive, createDate, hero` (`player_id`,`competitive`,`createDate`,`hero`),
  CONSTRAINT `FK_hero_general_stats_players` FOREIGN KEY (`player_id`) REFERENCES `players` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1023751 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for hero_specific_stats
-- ----------------------------
DROP TABLE IF EXISTS `hero_specific_stats`;
CREATE TABLE `hero_specific_stats` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `createDate` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `player_id` int(11) NOT NULL,
  `competitive` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `hero` varchar(10) NOT NULL,
  `damage_amplified_most_in_game` smallint(4) unsigned NOT NULL,
  `supercharger_assists_most_in_game` tinyint(3) unsigned NOT NULL,
  `damage_amplified` mediumint(8) unsigned NOT NULL,
  `damage_blocked_most_in_game` smallint(5) unsigned NOT NULL,
  `supercharger_assists` smallint(5) unsigned NOT NULL,
  `damage_blocked` int(11) unsigned NOT NULL,
  `hook_accuracy_best_in_game` float unsigned NOT NULL,
  `self_healing` int(11) unsigned NOT NULL,
  `hook_accuracy` float unsigned NOT NULL,
  `hooks_attempted` smallint(5) unsigned NOT NULL,
  `self_healing_most_in_game` smallint(5) unsigned NOT NULL,
  `enemies_hooked_most_in_game` tinyint(3) unsigned NOT NULL,
  `enemies_hooked` smallint(5) unsigned NOT NULL,
  `blaster_kills_most_in_game` tinyint(3) unsigned NOT NULL,
  `blaster_kills` smallint(5) unsigned NOT NULL,
  `players_resurrected_most_in_game` tinyint(3) unsigned NOT NULL,
  `players_resurrected` smallint(5) unsigned NOT NULL,
  `damage_reflected` int(11) unsigned NOT NULL,
  `damage_reflected_most_in_game` smallint(5) unsigned NOT NULL,
  `rocket_hammer_melee_accuracy` float unsigned NOT NULL,
  `players_knocked_back_most_in_game` tinyint(3) unsigned NOT NULL,
  `tesla_cannon_accuracy` float unsigned NOT NULL,
  `players_knocked_back` smallint(5) unsigned NOT NULL,
  `transcendence_healing_best` smallint(5) unsigned NOT NULL,
  `transcendence_healing` mediumint(8) unsigned NOT NULL,
  `death_blossom_kills` smallint(5) unsigned NOT NULL,
  `death_blossom_kills_most_in_game` tinyint(2) unsigned NOT NULL,
  `sound_barriers_provided_most_in_game` tinyint(2) unsigned NOT NULL,
  `sound_barriers_provided` smallint(5) unsigned NOT NULL,
  `enemies_hacked` smallint(5) unsigned NOT NULL,
  `enemies_empd_most_in_game` tinyint(2) unsigned NOT NULL,
  `enemies_hacked_most_in_game` tinyint(2) unsigned NOT NULL,
  `enemies_empd` smallint(4) unsigned NOT NULL,
  `biotic_grenade_kills` smallint(4) unsigned NOT NULL,
  `scoped_accuracy_best_in_game` float unsigned NOT NULL,
  `unscoped_accuracy_best_in_game` float unsigned NOT NULL,
  `enemies_slept` smallint(5) unsigned NOT NULL,
  `nano_boost_assists_most_in_game` tinyint(2) unsigned NOT NULL,
  `enemies_slept_most_in_game` tinyint(2) unsigned NOT NULL,
  `nano_boosts_applied_most_in_game` tinyint(2) unsigned NOT NULL,
  `unscoped_accuracy` float unsigned NOT NULL,
  `nano_boost_assists` smallint(5) unsigned NOT NULL,
  `scoped_accuracy` float unsigned NOT NULL,
  `nano_boosts_applied` smallint(5) unsigned NOT NULL,
  `mechs_called` smallint(5) unsigned NOT NULL,
  `self_destruct_kills_most_in_game` tinyint(2) unsigned NOT NULL,
  `mechs_called_most_in_game` tinyint(2) unsigned NOT NULL,
  `mech_deaths` smallint(5) unsigned NOT NULL,
  `self_destruct_kills` smallint(5) unsigned NOT NULL,
  `enemies_trapped_most_in_game` tinyint(2) unsigned NOT NULL,
  `concussion_mine_kills` smallint(5) unsigned NOT NULL,
  `rip_tire_kills` smallint(5) unsigned NOT NULL,
  `concussion_mine_kills_most_in_game` tinyint(2) unsigned NOT NULL,
  `rip_tire_kills_most_in_game` tinyint(2) unsigned NOT NULL,
  `enemies_trapped` smallint(5) unsigned NOT NULL,
  `whole_hog_kills_most_in_game` tinyint(2) unsigned NOT NULL,
  `whole_hog_kills` smallint(5) unsigned NOT NULL,
  `scatter_arrow_kills` smallint(5) unsigned NOT NULL,
  `scatter_arrow_kills_most_in_game` tinyint(2) unsigned NOT NULL,
  `dragonstrike_kills` smallint(5) unsigned NOT NULL,
  `dragonstrike_kills_most_in_game` tinyint(2) unsigned NOT NULL,
  `dragonblade_kills` smallint(5) unsigned NOT NULL,
  `dragonblade_kills_most_in_game` tinyint(2) unsigned NOT NULL,
  `sentry_kills` smallint(5) unsigned NOT NULL,
  `sentry_kills_most_in_game` tinyint(2) unsigned NOT NULL,
  `recon_kills_most_in_game` tinyint(2) unsigned NOT NULL,
  `tank_kills_most_in_game` tinyint(2) unsigned NOT NULL,
  `tank_kills` smallint(4) unsigned NOT NULL,
  `recon_kills` smallint(4) unsigned NOT NULL,
  `coalescence_healing_most_in_game` smallint(5) unsigned NOT NULL,
  `coalescence_healing` mediumint(8) unsigned NOT NULL,
  `secondary_fire_accuracy` float unsigned NOT NULL,
  `coalescence_kills` smallint(5) unsigned NOT NULL,
  `coalescence_kills_most_in_game` tinyint(2) unsigned NOT NULL,
  `meteor_strike_kills_most_in_game` tinyint(2) unsigned NOT NULL,
  `ability_damage_done` mediumint(8) unsigned NOT NULL,
  `shields_created` mediumint(8) unsigned NOT NULL,
  `shields_created_most_in_game` smallint(5) unsigned NOT NULL,
  `ability_damage_done_most_in_game` smallint(5) unsigned NOT NULL,
  `meteor_strike_kills` smallint(5) unsigned NOT NULL,
  `enemies_frozen` smallint(5) unsigned NOT NULL,
  `blizzard_kills_most_in_game` tinyint(2) unsigned NOT NULL,
  `blizzard_kills` smallint(5) unsigned NOT NULL,
  `enemies_frozen_most_in_game` tinyint(2) unsigned NOT NULL,
  `deadeye_kills_most_in_game` tinyint(2) unsigned NOT NULL,
  `fan_the_hammer_kills` smallint(5) unsigned NOT NULL,
  `fan_the_hammer_kills_most_in_game` tinyint(2) unsigned NOT NULL,
  `deadeye_kills` smallint(5) unsigned NOT NULL,
  `graviton_surge_kills` smallint(5) unsigned NOT NULL,
  `high_energy_kills` smallint(5) unsigned NOT NULL,
  `projected_barriers_applied_most_in_game` tinyint(2) unsigned NOT NULL,
  `projected_barriers_applied` smallint(5) unsigned NOT NULL,
  `graviton_surge_kills_most_in_game` tinyint(2) unsigned NOT NULL,
  `high_energy_kills_most_in_game` tinyint(2) unsigned NOT NULL,
  `primary_fire_accuracy` float unsigned NOT NULL,
  `melee_kills_most_in_game` tinyint(2) unsigned NOT NULL,
  `jump_pack_kills` smallint(5) unsigned NOT NULL,
  `jump_pack_kills_most_in_game` tinyint(2) unsigned NOT NULL,
  `primal_rage_kills` smallint(4) unsigned NOT NULL,
  `primal_rage_kills_most_in_game` tinyint(2) unsigned NOT NULL,
  `melee_kills` smallint(4) unsigned NOT NULL,
  `primal_rage_melee_accuracy` float unsigned NOT NULL,
  `scoped_critical_hits` smallint(5) unsigned NOT NULL,
  `scoped_critical_hits_most_in_game` tinyint(2) unsigned NOT NULL,
  `venom_mine_kills_most_in_game` tinyint(2) unsigned NOT NULL,
  `venom_mine_kills` smallint(5) unsigned NOT NULL,
  `charge_kills_most_in_game` tinyint(2) unsigned NOT NULL,
  `charge_kills` smallint(5) unsigned NOT NULL,
  `fire_strike_kills` smallint(5) unsigned NOT NULL,
  `earthshatter_kills_most_in_game` tinyint(2) unsigned NOT NULL,
  `earthshatter_kills` smallint(5) unsigned NOT NULL,
  `fire_strike_kills_most_in_game` tinyint(2) unsigned NOT NULL,
  `molten_core_kills` smallint(5) unsigned NOT NULL,
  `torbjorn_kills` smallint(5) unsigned NOT NULL,
  `armor_packs_created` smallint(5) unsigned NOT NULL,
  `armor_packs_created_most_in_game` tinyint(2) unsigned NOT NULL,
  `turret_kills_most_in_game` tinyint(2) unsigned NOT NULL,
  `torbjorn_kills_most_in_game` tinyint(2) unsigned NOT NULL,
  `molten_core_kills_most_in_game` tinyint(2) unsigned NOT NULL,
  `turret_kills` smallint(5) unsigned NOT NULL,
  `rocket_direct_hits_most_in_game` tinyint(3) unsigned NOT NULL,
  `barrage_kills` smallint(5) unsigned NOT NULL,
  `barrage_kills_most_in_game` tinyint(2) unsigned NOT NULL,
  `rocket_direct_hits` mediumint(8) unsigned NOT NULL,
  `players_teleported_most_in_game` tinyint(2) unsigned NOT NULL,
  `sentry_turret_kills_most_in_game` tinyint(2) unsigned NOT NULL,
  `sentry_turret_kills` smallint(5) unsigned NOT NULL,
  `players_teleported` smallint(5) unsigned NOT NULL,
  `health_recovered` mediumint(8) unsigned NOT NULL,
  `health_recovered_most_in_game` smallint(5) unsigned NOT NULL,
  `pulse_bombs_attached` smallint(5) unsigned NOT NULL,
  `pulse_bomb_kills` smallint(5) unsigned NOT NULL,
  `pulse_bomb_kills_most_in_game` tinyint(2) unsigned NOT NULL,
  `pulse_bombs_attached_most_in_game` tinyint(2) unsigned NOT NULL,
  `tactical_visor_kills` smallint(5) unsigned NOT NULL,
  `tactical_visor_kills_most_in_game` tinyint(2) unsigned NOT NULL,
  `biotic_fields_deployed` smallint(5) unsigned NOT NULL,
  `biotic_field_healing_done` mediumint(8) unsigned NOT NULL,
  `helix_rocket_kills` smallint(5) unsigned NOT NULL,
  `helix_rocket_kills_most_in_game` tinyint(2) unsigned NOT NULL,
  `armor_provided_most_in_game` smallint(5) unsigned NOT NULL,
  `armor_provided` smallint(5) unsigned NOT NULL,
  `deflection_kills` smallint(5) unsigned NOT NULL,
  `amplification_matrix_assists` smallint(5) unsigned NOT NULL DEFAULT '0',
  `amplification_matrix_assists_best_in_game` smallint(5) unsigned NOT NULL DEFAULT '0',
  `immortality_field_deaths_prevented` smallint(5) unsigned NOT NULL DEFAULT '0',
  `amplification_matrix_casts_most_in_game` smallint(5) unsigned NOT NULL DEFAULT '0',
  `amplification_matrix_casts` smallint(5) unsigned NOT NULL DEFAULT '0',
  `healing_accuracy` smallint(5) unsigned NOT NULL DEFAULT '0',
  `immortality_field_deaths_prevented_most_in_game` smallint(5) unsigned NOT NULL DEFAULT '0',
  `healing_amplified_most_in_game` smallint(5) unsigned NOT NULL DEFAULT '0',
  `healing_accuracy_best_in_game` smallint(5) unsigned NOT NULL DEFAULT '0',
  `healing_amplified` smallint(5) unsigned NOT NULL DEFAULT '0',
  `storm_arrow_kills_most_in_game` smallint(5) unsigned NOT NULL DEFAULT '0',
  `storm_arrow_kills` smallint(5) unsigned NOT NULL DEFAULT '0',
  `inspire_uptime_percentage` smallint(5) unsigned NOT NULL DEFAULT '0',
  `jump_kills` smallint(5) unsigned NOT NULL DEFAULT '0',
  `weapon_kills` smallint(5) unsigned NOT NULL DEFAULT '0',
  `average_energy_best_in_game` smallint(5) unsigned NOT NULL DEFAULT '0',
  `average_energy` smallint(5) unsigned NOT NULL DEFAULT '0',
  `overload_kills_most_in_game` smallint(5) unsigned NOT NULL DEFAULT '0',
  `overload_kills` smallint(5) unsigned NOT NULL DEFAULT '0',
  `dynamite_kills` smallint(5) unsigned NOT NULL DEFAULT '0',
  `dynamite_kills_most_in_game` smallint(5) unsigned NOT NULL DEFAULT '0',
  `coach_gun_kills_most_in_game` smallint(5) unsigned NOT NULL DEFAULT '0',
  `coach_gun_kills` smallint(5) unsigned NOT NULL DEFAULT '0',
  `bob_kills` smallint(5) unsigned NOT NULL DEFAULT '0',
  `bob_kills_most_in_game` smallint(5) unsigned NOT NULL DEFAULT '0',
  `scoped_critical_hit_kills` smallint(5) unsigned NOT NULL DEFAULT '0',
  `immortality_field_death_prevented` smallint(5) unsigned NOT NULL DEFAULT '0',
  `immortality_field_death_prevented_most_in_game` smallint(5) unsigned NOT NULL DEFAULT '0',
  `scoped_critical_hit_accuracy` smallint(5) unsigned NOT NULL DEFAULT '0',
  `direct_hit_accuracy` smallint(5) unsigned NOT NULL DEFAULT '0',
  `hammer_kills_most_in_game` smallint(5) unsigned NOT NULL DEFAULT '0',
  `hammer_kills` smallint(5) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `player_id, competitive` (`player_id`,`competitive`),
  KEY `hero` (`hero`),
  KEY `competitive` (`competitive`),
  KEY `player_id, competitive, createDate, hero` (`player_id`,`competitive`,`createDate`,`hero`),
  CONSTRAINT `FK_hero_specific_stats_players` FOREIGN KEY (`player_id`) REFERENCES `players` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1023751 DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;

-- ----------------------------
-- Table structure for overall_stats
-- ----------------------------
DROP TABLE IF EXISTS `overall_stats`;
CREATE TABLE `overall_stats` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `createDate` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `player_id` int(11) DEFAULT NULL,
  `competitive` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `comprank` smallint(6) DEFAULT NULL,
  `level` tinyint(4) DEFAULT NULL,
  `prestige` tinyint(4) DEFAULT NULL,
  `games` int(11) DEFAULT NULL,
  `wins` int(11) DEFAULT NULL,
  `losses` int(11) DEFAULT NULL,
  `ties` int(11) DEFAULT NULL,
  `win_rate` float DEFAULT NULL,
  `tier` varchar(10) DEFAULT NULL,
  `tier_image` varchar(150) DEFAULT NULL,
  `avatar` varchar(150) DEFAULT NULL,
  `rank_image` varchar(150) DEFAULT NULL,
  `endorsement_level` tinyint(1) unsigned DEFAULT NULL,
  `endorsement_shotcaller` float DEFAULT NULL,
  `endorsement_teammate` float DEFAULT NULL,
  `endorsement_sportsmanship` float DEFAULT NULL,
  `prestige_image` varchar(150) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `tier` (`tier`),
  KEY `competitive` (`competitive`),
  KEY `player_id, competitive, createDate` (`player_id`,`competitive`,`createDate`),
  CONSTRAINT `FK_overall_stats_players` FOREIGN KEY (`player_id`) REFERENCES `players` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=63751 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for players
-- ----------------------------
DROP TABLE IF EXISTS `players`;
CREATE TABLE `players` (
  `id` int(3) NOT NULL AUTO_INCREMENT,
  `createDate` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modifyDate` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `battleTag` varchar(25) NOT NULL,
  `name` varchar(25) NOT NULL,
  `active` bit(1) NOT NULL,
  `failCount` tinyint(3) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `battleTag` (`battleTag`),
  KEY `active` (`active`),
  KEY `name` (`name`),
  KEY `modifyDate` (`modifyDate`),
  KEY `modifyDate, id` (`modifyDate`,`id`)
) ENGINE=InnoDB AUTO_INCREMENT=214 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for rolling_average_stats
-- ----------------------------
DROP TABLE IF EXISTS `rolling_average_stats`;
CREATE TABLE `rolling_average_stats` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `createDate` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `player_id` int(11) DEFAULT NULL,
  `competitive` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `solo_kills` float DEFAULT '0',
  `hero_damage_done` float DEFAULT '0',
  `objective_time` float DEFAULT '0',
  `final_blows` float DEFAULT '0',
  `healing_done` float DEFAULT '0',
  `deaths` float DEFAULT '0',
  `all_damage_done` float DEFAULT '0',
  `eliminations` float DEFAULT '0',
  `objective_kills` float DEFAULT '0',
  `time_spent_on_fire` float DEFAULT '0',
  `barrier_damage_done` float DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `competitive` (`competitive`),
  KEY `FK__players` (`player_id`),
  KEY `createDate` (`createDate`),
  CONSTRAINT `FK__players` FOREIGN KEY (`player_id`) REFERENCES `players` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=63751 DEFAULT CHARSET=utf8;

